In [49]:
import numpy as np

In [50]:
# Integer array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [51]:
# Nested array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [52]:
# array filled with zeros
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [53]:
# 3x5 array filled with ones
np.ones((3,5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
# 4x5 array filled with 1.61
np.full((3,5), 1.61)

array([[1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61]])

In [55]:
# arithmetic sequence, start at 0 end at 20 common diffrence 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
# five values evenly spaced between 4.3 and 7.9
np.linspace(4.3, 7.9, 5)

array([4.3, 5.2, 6.1, 7. , 7.9])

In [57]:
# 3x3 array of uniformly distributed random value
np.random.random((3,3))

array([[0.56395904, 0.72323905, 0.99241125],
       [0.1526568 , 0.86513338, 0.87054164],
       [0.59499012, 0.2913263 , 0.23269369]])

In [58]:
# normally distributed random values with mean 3 and standard eviation 5
np.random.normal(3,5,(3,3))

array([[ 4.00840524, -2.91775667, 12.30100963],
       [-0.82048354,  7.5262097 ,  7.94201186],
       [ 4.82122636,  4.15189979,  6.88832073]])

In [59]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1.5e-323, 2.0e-323, 2.5e-323])

In [60]:
import time
np.random.seed(int(time.time())) # seed for reproducibility

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print(x1)
print(x2)
print(x3)

[8 8 7 9 6 1]
[[2 5 0 4]
 [5 8 6 2]
 [8 1 0 2]]
[[[1 4 1 7 7]
  [2 0 1 4 0]
  [8 6 6 5 5]
  [3 2 5 0 9]]

 [[4 8 4 4 2]
  [2 8 7 7 5]
  [9 2 9 1 8]
  [2 4 5 6 8]]

 [[0 7 2 4 7]
  [9 7 0 3 0]
  [5 5 2 1 1]
  [6 7 0 7 8]]]


In [61]:
print("x3 shape: ", x3.shape)
print("x3 dimension: ", x3.ndim)
print("x3 size: ", x3.size)
print("x3 data type: ", x3.dtype)
print("x3 item size: ", x3.itemsize)
print("x3 nbytes: ", x3.nbytes)

x3 shape:  (3, 4, 5)
x3 dimension:  3
x3 size:  60
x3 data type:  int64
x3 item size:  8
x3 nbytes:  480


In [62]:
# indexing array
print(x1)
print(x1[4])
print(x2)
print(x2[2][3], x2[2,3])

[8 8 7 9 6 1]
6
[[2 5 0 4]
 [5 8 6 2]
 [8 1 0 2]]
2 2


In [63]:
print(x1)
print(x1[1:5])
print(x1[:4])
print(x1[1:])
print(x1[::2])
print(x1[::-1])

[8 8 7 9 6 1]
[8 7 9 6]
[8 8 7 9]
[8 7 9 6 1]
[8 7 6]
[1 6 9 7 8 8]


In [68]:
print(x2)
print(x2[1:])
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[::-1, ::-1])

[[2 5 0 4]
 [5 8 6 2]
 [8 1 0 2]]
[[2 5 0]
 [5 8 6]]
[[2 0]
 [5 6]
 [8 0]]


In [20]:
# np array slicing provides a view not copy, so any changes to view will affect original array
# for copying data or slices
sb_cp = x2[:2, :2].copy()
sb_cp

array([[9, 5],
       [1, 3]])

In [21]:
# Reshaping array
# size of initial array must match the size of resized array
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x = np.array([1,2,3])
print(x.reshape((1,3)))

print(x[np.newaxis, :])
print(x.reshape((3,1)))
print(x[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [23]:
# splitting an array

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)



[1 2 3] [99 99] [3 2 1]


In [24]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
up, lw = np.vsplit(grid, [2])
print(up)
print(lw)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [26]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [27]:
np.pi


3.141592653589793

In [28]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [29]:
np.add.reduce(x)

np.int64(15)

In [30]:
np.multiply.reduce(x)

np.int64(120)

In [31]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [32]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])