In [2]:
import numpy as np

In [4]:
# Integer array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [5]:
# Nested array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# array filled with zeros
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [9]:
# 3x5 array filled with ones
np.ones((3,5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# 4x5 array filled with 1.61
np.full((3,5), 1.61)

array([[1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61]])

In [12]:
# arithmetic sequence, start at 0 end at 20 common diffrence 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# five values evenly spaced between 4.3 and 7.9
np.linspace(4.3, 7.9, 5)

array([4.3, 5.2, 6.1, 7. , 7.9])

In [16]:
# 3x3 array of uniformly distributed random value
np.random.random((3,3))

array([[0.26636701, 0.87343892, 0.52011525],
       [0.01996166, 0.11443212, 0.71520053],
       [0.63933197, 0.35620773, 0.09094548]])

In [20]:
# normally distributed random values with mean 3 and standard eviation 5
np.random.normal(3,5,(3,3))

array([[5.18312941, 7.87732672, 1.38198963],
       [0.83636183, 9.82134895, 4.55876883],
       [0.74487267, 7.90750463, 0.4709276 ]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [3]:
import time
np.random.seed(int(time.time())) # seed for reproducibility

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print(x1)
print(x2)
print(x3)

NameError: name 'np' is not defined

In [35]:
print("x3 shape: ", x3.shape)
print("x3 dimension: ", x3.ndim)
print("x3 size: ", x3.size)
print("x3 data type: ", x3.dtype)
print("x3 item size: ", x3.itemsize)
print("x3 nbytes: ", x3.nbytes)

x3 shape:  (3, 4, 5)
x3 dimension:  3
x3 size:  60
x3 data type:  int64
x3 item size:  8
x3 nbytes:  480


In [48]:
# indexing array
print(x1)
print(x1[4])
print(x2)
print(x2[2][3], x2[2,3])

[2 6 7 9 4 7]
4
[[1 6 1 8]
 [5 2 1 5]
 [7 5 3 4]]
4 4


In [2]:
print(x1)
print(x1[1:5])
print(x1[:4])
print(x1[1:])
print(x1[::2])
print(x1[::-1])

NameError: name 'x1' is not defined

In [1]:
print(x2)
print(x2[1:])
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[::-1, ::-1])

NameError: name 'x2' is not defined

In [60]:
# np array slicing provides a view not copy, so any changes to view will affect original array
# for copying data or slices
sb_cp = x2[:2, :2].copy()
sb_cp

array([[1, 6],
       [5, 2]])

In [62]:
# Reshaping array
# size of initial array must match the size of resized array
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
x = np.array([1,2,3])
print(x.reshape((1,3)))

print(x[np.newaxis, :])
print(x.reshape((3,1)))
print(x[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [64]:
# splitting an array

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)



[1 2 3] [99 99] [3 2 1]


In [66]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
up, lw = np.vsplit(grid, [2])
print(up)
print(lw)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [69]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [73]:
np.pi


3.141592653589793

In [80]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [81]:
np.add.reduce(x)

np.int64(15)

In [82]:
np.multiply.reduce(x)

np.int64(120)

In [84]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [85]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])