In [2]:
import numpy as np

In [4]:
# Integer array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [5]:
# Nested array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# array filled with zeros
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [9]:
# 3x5 array filled with ones
np.ones((3,5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# 4x5 array filled with 1.61
np.full((3,5), 1.61)

array([[1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61]])

In [12]:
# arithmetic sequence, start at 0 end at 20 common diffrence 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# five values evenly spaced between 4.3 and 7.9
np.linspace(4.3, 7.9, 5)

array([4.3, 5.2, 6.1, 7. , 7.9])

In [16]:
# 3x3 array of uniformly distributed random value
np.random.random((3,3))

array([[0.26636701, 0.87343892, 0.52011525],
       [0.01996166, 0.11443212, 0.71520053],
       [0.63933197, 0.35620773, 0.09094548]])

In [20]:
# normally distributed random values with mean 3 and standard eviation 5
np.random.normal(3,5,(3,3))

array([[5.18312941, 7.87732672, 1.38198963],
       [0.83636183, 9.82134895, 4.55876883],
       [0.74487267, 7.90750463, 0.4709276 ]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [26]:
import time
np.random.seed(time.time) # seed for reproducibility

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, (3,4))
x3 = np.random.randint(10, (3,4,5))

x1
x2
x3

TypeError: Cannot cast scalar from dtype('O') to dtype('int64') according to the rule 'safe'