In [2]:
import numpy as np

In [4]:
# Integer array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [5]:
# Nested array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# array filled with zeros
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [9]:
# 3x5 array filled with ones
np.ones((3,5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# 4x5 array filled with 1.61
np.full((3,5), 1.61)

array([[1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61],
       [1.61, 1.61, 1.61, 1.61, 1.61]])

In [12]:
# arithmetic sequence, start at 0 end at 20 common diffrence 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])