Create a NumPy array of zeros with shape (3, 4).


In [3]:
import numpy as np
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Generate an array of 20 random numbers as integers ranging between 1 and 10. Reshape the array
into a 4x5 matrix.

In [4]:
r = np.random.uniform(1,10,20)
r.reshape((4,5))

array([[4.60830469, 5.12494446, 9.06788813, 8.03392585, 4.08995829],
       [4.12952892, 2.24403334, 1.84136445, 9.03708817, 5.99175813],
       [3.45131933, 7.13472739, 9.68181241, 3.8796165 , 6.79907305],
       [8.02466551, 8.66276584, 4.16865415, 7.17512441, 1.1793361 ]])

Create a 5x5 identity matrix and extract the diagonal elements into a 1D array.

In [5]:
mat = np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])