Create a NumPy array of zeros with shape (3, 4).


In [3]:
import numpy as np
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Generate an array of 20 random numbers as integers ranging between 1 and 10. Reshape the array
into a 4x5 matrix.

In [4]:
r = np.random.uniform(1,10,20)
r.reshape((4,5))

array([[4.60830469, 5.12494446, 9.06788813, 8.03392585, 4.08995829],
       [4.12952892, 2.24403334, 1.84136445, 9.03708817, 5.99175813],
       [3.45131933, 7.13472739, 9.68181241, 3.8796165 , 6.79907305],
       [8.02466551, 8.66276584, 4.16865415, 7.17512441, 1.1793361 ]])

Create a 5x5 identity matrix and extract the diagonal elements into a 1D array.

In [11]:
mat = np.identity(5)
print(mat)
diagonal = mat.diagonal()
diagonal

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([1., 1., 1., 1., 1.])

Create matrix and access rows and columns
● create a 4x5 array of even numbers: 10, 12, 14, ...
● extract third column
● set the fourth row to 1,2,3,4,5

In [19]:
even = np.arange(10, 50, 2).reshape((4,5))
print(even)
thrd = even[:, 2:3]
print(thrd)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
[[14]
 [24]
 [34]
 [44]]


consider two vectors
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])
Do the following using a single one-line vectorized operation.
● Extract all test scores that are smaller than 130
● Extract all test scores by Statira
● Add 10 points to Roxana’s scores. (You need to extract it first.)

In [25]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])

print(score[score>130])

[141 132]
